// Generated by organizer.html — circle centers are offset from the real spots.
window.HUNT = {
 "title": "UST Scavenger Hunt",
 "returnBy": "19:55",
 "radius": 20,
 "start": {
  "name": "Brady LL Desk",
  "lat": 44.944391,
  "lng": -93.19015
 },
 "stops": [
  {
   "id": 1,
   "photo": "photos/poi01.jpg",
   "lat": 44.942862,
   "lng": -93.189505
  },
  {
   "id": 2,
   "photo": "photos/poi02.jpg",
   "lat": 44.94225,
   "lng": -93.189652
  },
  {
   "id": 3,
   "photo": "photos/poi03.jpg",
   "lat": 44.944744,
   "lng": -93.18743
  },
  {
   "id": 4,
   "photo": "photos/poi04.jpg",
   "lat": 44.93938,
   "lng": -93.193277
  },
  {
   "id": 5,
   "photo": "photos/poi05.jpg",
   "lat": 44.94039,
   "lng": -93.190068
  },
  {
   "id": 6,
   "photo": "photos/poi06.jpg",
   "lat": 44.940671,
   "lng": -93.193229
  },
  {
   "id": 7,
   "photo": "photos/poi07.jpg",
   "lat": 44.938965,
   "lng": -93.195857
  },
  {
   "id": 8,
   "photo": "photos/poi08.jpg",
   "lat": 44.94128,
   "lng": -93.188885
  },
  {
   "id": 9,
   "photo": "photos/poi09.jpg",
   "lat": 44.941155,
   "lng": -93.194933
  },
  {
   "id": 10,
   "photo": "photos/poi10.jpg",
   "lat": 44.941022,
   "lng": -93.187647
  },
  {
   "id": 11,
   "photo": "photos/poi11.jpg",
   "lat": 44.944225,
   "lng": -93.188204
  },
  {
   "id": 12,
   "photo": "photos/poi12.jpg",
   "lat": 44.944228,
   "lng": -93.188477
  },
  {
   "id": 13,
   "photo": "photos/poi13.jpg",
   "lat": 44.94069,
   "lng": -93.19515
  },
  {
   "id": 14,
   "photo": "photos/poi14.jpg",
   "lat": 44.938571,
   "lng": -93.195385
  },
  {
   "id": 15,
   "photo": "photos/poi15.jpg",
   "lat": 44.939335,
   "lng": -93.195773
  }
 ]
};
